name: build-workflow
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: build-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          wget https://storage.googleapis.com/kubernetes-helm/helm-v2.8.2-linux-amd64.tar.gz -O /tmp/helm-v2.8.2-linux-amd64.tar.gz
          mkdir /tmp/bin -p; tar xzf /tmp/helm-v2.8.2-linux-amd64.tar.gz -C /tmp/bin --strip-components=1;
          PATH=/tmp/bin:$PATH helm init --client-only
          cd base-image && make
          cd ../config-reloader && make build-image
          cd ../charts/log-router
          PATH=$PATH:/tmp/bin make helm-package